// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// User Loading
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

// Clear Error
export const CLEAR_ERROR_REQUEST = 'CLEAR_ERROR_REQUEST';
export const CLEAR_ERROR_SUCCESS = 'CLEAR_ERROR_SUCCESS';
export const CLEAR_ERROR_FAILURE = 'CLEAR_ERROR_FAILURE';

// Member Uploading
export const MEMBER_UPLOADING_REQUEST = 'MEMBER_UPLOADING_REQUEST';
export const MEMBER_UPLOADING_SUCCESS = 'MEMBER_UPLOADING_SUCCESS';
export const MEMBER_UPLOADING_FAILURE = 'MEMBER_UPLOADING_FAILURE';

// Member LIST
export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS';
export const MEMBER_LIST_FAILURE = 'MEMBER_LIST_FAILURE';

// Member Inquiries
export const MEMBER_INQUIRIES_REQUEST = 'MEMBER_INQUIRIES_REQUEST';
export const MEMBER_INQUIRIES_SUCCESS = 'MEMBER_INQUIRIES_SUCCESS';
export const MEMBER_INQUIRIES_FAILURE = 'MEMBER_INQUIRIES_FAILURE';

// Member Singlelist
export const MEMBER_SINGLELIST_REQUEST = 'MEMBER_SINGLELIST_REQUEST';
export const MEMBER_SINGLELIST_SUCCESS = 'MEMBER_SINGLELIST_SUCCESS';
export const MEMBER_SINGLELIST_FAILURE = 'MEMBER_SINGLELIST_FAILURE';

// Member Updatelist
export const MEMBER_UPDATELIST_REQUEST = 'MEMBER_UPDATELIST_REQUEST';
export const MEMBER_UPDATELIST_SUCCESS = 'MEMBER_UPDATELIST_SUCCESS';
export const MEMBER_UPDATELIST_FAILURE = 'MEMBER_UPDATELIST_FAILURE';

// Member Delete
export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST';
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS';
export const MEMBER_DELETE_FAILURE = 'MEMBER_DELETE_FAILURE';

// Member Warm
export const MEMBER_WARN_REQUEST = 'MEMBER_WARN_REQUEST';
export const MEMBER_WARN_SUCCESS = 'MEMBER_WARN_SUCCESS';
export const MEMBER_WARN_FAILURE = 'MEMBER_WARN_FAILURE';

// Member Warmlist
export const MEMBER_WARNLIST_REQUEST = 'MEMBER_WARNLIST_REQUEST';
export const MEMBER_WARNLIST_SUCCESS = 'MEMBER_WARNLIST_SUCCESS';
export const MEMBER_WARNLIST_FAILURE = 'MEMBER_WARNLIST_FAILURE';

// Member Removewarnmember
export const MEMBER_REMOVEWARNMEMBER_REQUEST = 'MEMBER_REMOVEWARNMEMBER_REQUEST';
export const MEMBER_REMOVEWARNMEMBER_SUCCESS = 'MEMBER_REMOVEWARNMEMBER_SUCCESS';
export const MEMBER_REMOVEWARNMEMBER_FAILURE = 'MEMBER_REMOVEWARNMEMBER_FAILURE';

// Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';


